server:
  port: 4531



spring:
  application:
    name: bigGod
  thymeleaf:
    cache: false
    encoding: 'UTF-8'
    mode: 'HTML5'
  datasource:
    dialect: mysql
    url: 'jdbc:mysql://172.20.10.15:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&allowMultiQueries=true'
    username: 'root'
    password: 'root'
    driver-class-name: 'com.mysql.jdbc.Driver'
    type: com.alibaba.druid.pool.DruidDataSource


mybatis:
  mapper-locations: 'classpath*:/mapper/*.xml'


info:
  app:
    name: bigGod
    encoding: UTF-8
    java:
      source: 1.8.0_92
      target: 1.8.0_92
eureka:
  instance:
    metadata-map:
      my-metadata: 我自定义的元数据
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:4523/eureka


