server:
  port: 4500

spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
    encoding: 'UTF-8'
    mode: 'HTML5'
  datasource:
    url: 'jdbc:mysql://172.20.10.15:3306/testdatabase?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&allowMultiQueries=true'
    username: 'root'
    password: 'root'
    driver-class-name: 'com.mysql.jdbc.Driver'
    type: com.alibaba.druid.pool.DruidDataSource
    dialect: mysql
